### ISSUE TITLE
DUNE interface condition

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/spatial-model-editor#36]
- DUNE specifies interface condition in terms of the derivative of species concentration w.r.t normal vector of boundary surface
- SBML models instead typically specify a reaction involving species on both sides of boundary

- need to think about how to convert the latter into the former
   - DUNE has access to concentrations on both sides of the boundary, so in principle possible

**Comment by SoilRos** [comment]
There are two options for this solving this:
1. The interface is represented as a thin membrane in 2D. In such a case, the mesh has to represent the membrane and the input to `DUNE` has to include another model for each membrane. This would not need any modification from the `DUNE` side as the membrane will be considered a compartment like the others. A constraint with this approach is that it also needs the a definition of diffusion coefficients on the membrane. Hence, this work would have to be made by the user, or by the editor.
2. The interface is represented as other problem in a 1D manifold. In such case, DUNE would have to resolve the system in there as well. This is more complicated because on the mathematics and the software.

**Comment by lkeegan** [comment]
Thanks Santiago - to me option 1 sounds like it should be fine - I'll see what Sven thinks.

**Comment by lkeegan** [comment]
two possibilities for what happens at the interface between two compartments in DUNE:

1. Same species exists on both sides: species diffuses freely across interface (diff const can be different in the two compartments)
2. Species only present in one compartment: zero-flux neumann boundary condition at interface by default (also dirichelet could be possible but not currently implemented)

NB: diffusion "constant" & initial reactions can be all be functions of space in ini file: `x` & `y`
(note this implies `x`, `y`, and also `pi` and `dim` are reserved and should not be used as species names in the DUNE ini file)
